[global]
hardware = rx888 # use built-in rx888 driver, configured in [rx888]
status = hf-status.local       # DNS name for receiver status and commands
data = hf-data.local
samprate = 12000        # default output sample rate
mode = usb 		# default receive mode
# rest are defaults
#ttl = 1
ttl = 0                 # Too many WD sites don't have IGMP aware ethernet swtiches, so don't send radiod multicast packets out the ethernet port.
fft-threads = 1
fft-internal-threads = 0
#iface = enp1s0

