.TH "ax25_frame" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ax25_frame
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBdest\fP [CALL_LEN]"
.br
.ti -1c
.RI "char \fBsource\fP [CALL_LEN]"
.br
.ti -1c
.RI "struct \fBdigi\fP \fBdigipeaters\fP [MAX_DIGI]"
.br
.ti -1c
.RI "int \fBndigi\fP"
.br
.ti -1c
.RI "int \fBcontrol\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "char \fBinformation\fP [MAX_INFO]"
.br
.ti -1c
.RI "size_t \fBinfo_len\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
