.TH "bandplan" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bandplan
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBlower\fP"
.br
.ti -1c
.RI "double \fBupper\fP"
.br
.ti -1c
.RI "char \fBdescription\fP [160]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
