.TH "FCD_CAPS_STRUCT" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FCD_CAPS_STRUCT \- FCD capabilities that depend on both hardware and firmware\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <fcd\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBhasBiasT\fP"
.br
.ti -1c
.RI "unsigned char \fBhasCellBlock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FCD capabilities that depend on both hardware and firmware\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned char FCD_CAPS_STRUCT::hasBiasT"
Whether FCD has hardware bias tee (1=yes, 0=no) 
.SS "unsigned char FCD_CAPS_STRUCT::hasCellBlock"
Whether FCD has cellular blocking\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
