.TH "fx_known_device" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fx_known_device
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBvid\fP"
.br
.ti -1c
.RI "uint16_t \fBpid\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBdesignation\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
