.TH "hb15_state" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb15_state
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBcoeffs\fP [4]"
.br
.ti -1c
.RI "float \fBeven_samples\fP [4]"
.br
.ti -1c
.RI "float \fBodd_samples\fP [4]"
.br
.ti -1c
.RI "float \fBold_odd_samples\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
