.TH "hdlc" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hdlc
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBframe\fP [16384]"
.br
.ti -1c
.RI "size_t \fBframe_bits\fP"
.br
.ti -1c
.RI "int \fBflag_seen\fP"
.br
.ti -1c
.RI "int \fBlast_bits\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
