.TH "hid_device_" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hid_device_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "libusb_device_handle * \fBdevice_handle\fP"
.br
.ti -1c
.RI "int \fBinput_endpoint\fP"
.br
.ti -1c
.RI "int \fBoutput_endpoint\fP"
.br
.ti -1c
.RI "int \fBinput_ep_max_packet_size\fP"
.br
.ti -1c
.RI "int \fBinterface\fP"
.br
.ti -1c
.RI "int \fBmanufacturer_index\fP"
.br
.ti -1c
.RI "int \fBproduct_index\fP"
.br
.ti -1c
.RI "int \fBserial_index\fP"
.br
.ti -1c
.RI "int \fBblocking\fP"
.br
.ti -1c
.RI "pthread_t \fBthread\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcondition\fP"
.br
.ti -1c
.RI "pthread_barrier_t \fBbarrier\fP"
.br
.ti -1c
.RI "int \fBshutdown_thread\fP"
.br
.ti -1c
.RI "int \fBcancelled\fP"
.br
.ti -1c
.RI "struct libusb_transfer * \fBtransfer\fP"
.br
.ti -1c
.RI "struct \fBinput_report\fP * \fBinput_reports\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
