.TH "idtable" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
idtable
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBfreq\fP"
.br
.ti -1c
.RI "float \fBtone\fP"
.br
.ti -1c
.RI "char \fBid\fP [128]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
