.TH "inverse_cache" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inverse_cache
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBinverse_cache\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBinverse_cache\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct sockaddr_storage \fBsock\fP"
.br
.ti -1c
.RI "char \fBhostport\fP [2 *NI_MAXHOST+NI_MAXSERV+5]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
