.TH "lang_map_entry" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lang_map_entry
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBstring_code\fP"
.br
.ti -1c
.RI "uint16_t \fBusb_code\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
