.TH "notchfilter" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
notchfilter
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "complex double \fBosc_phase\fP"
.br
.ti -1c
.RI "complex double \fBosc_step\fP"
.br
.ti -1c
.RI "complex float \fBdcstate\fP"
.br
.ti -1c
.RI "float \fBbw\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
