.TH "packet" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packet
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBpacket\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBrtp_header\fP \fBrtp\fP"
.br
.ti -1c
.RI "uint8_t const  * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.ti -1c
.RI "uint8_t \fBcontent\fP [PKTSIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
