.TH "pcmstream" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcmstream
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBssrc\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "struct sockaddr \fBsender\fP"
.br
.ti -1c
.RI "char const  * \fBsource\fP"
.br
.ti -1c
.RI "int \fBframesize\fP"
.br
.ti -1c
.RI "long long \fBbytes_received\fP"
.br
.ti -1c
.RI "struct \fBrtp_header\fP \fBlast_header\fP"
.br
.ti -1c
.RI "int \fBlast_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
