.TH "pll" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pll
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBsamprate\fP"
.br
.ti -1c
.RI "uint32_t \fBvco_phase\fP"
.br
.ti -1c
.RI "int32_t \fBvco_step\fP"
.br
.ti -1c
.RI "float \fBintegrator_gain\fP"
.br
.ti -1c
.RI "float \fBprop_gain\fP"
.br
.ti -1c
.RI "float \fBintegrator\fP"
.br
.ti -1c
.RI "float \fBbw\fP"
.br
.ti -1c
.RI "float \fBdamping\fP"
.br
.ti -1c
.RI "float \fBlower_limit\fP"
.br
.ti -1c
.RI "float \fBupper_limit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
