.TH "pt_table" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pt_table
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBsamprate\fP"
.br
.ti -1c
.RI "unsigned int \fBchannels\fP"
.br
.ti -1c
.RI "enum encoding \fBencoding\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
