.TH "ram_poke_context" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ram_poke_context
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "libusb_device_handle * \fBdevice\fP"
.br
.ti -1c
.RI "ram_mode \fBmode\fP"
.br
.ti -1c
.RI "size_t \fBtotal\fP"
.br
.ti -1c
.RI "size_t \fBcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
