.TH "rtcp_sr" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtcp_sr
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBssrc\fP"
.br
.ti -1c
.RI "int64_t \fBntp_timestamp\fP"
.br
.ti -1c
.RI "unsigned int \fBrtp_timestamp\fP"
.br
.ti -1c
.RI "unsigned int \fBpacket_count\fP"
.br
.ti -1c
.RI "unsigned int \fBbyte_count\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
