.TH "rtcp_sdes" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtcp_sdes
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum sdes_type \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBssrc\fP"
.br
.ti -1c
.RI "int \fBmlen\fP"
.br
.ti -1c
.RI "char \fBmessage\fP [256]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
