.TH "rtcp_rr" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtcp_rr
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBssrc\fP"
.br
.ti -1c
.RI "int \fBlost_fract\fP"
.br
.ti -1c
.RI "int \fBlost_packets\fP"
.br
.ti -1c
.RI "int \fBhighest_seq\fP"
.br
.ti -1c
.RI "int \fBjitter\fP"
.br
.ti -1c
.RI "int \fBlsr\fP"
.br
.ti -1c
.RI "int \fBdlsr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
