.TH "rtp_header" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtp_header
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint16_t \fBseq\fP"
.br
.ti -1c
.RI "uint32_t \fBtimestamp\fP"
.br
.ti -1c
.RI "uint32_t \fBssrc\fP"
.br
.ti -1c
.RI "bool \fBmarker\fP:1"
.br
.ti -1c
.RI "bool \fBpad\fP:1"
.br
.ti -1c
.RI "bool \fBextension\fP:1"
.br
.ti -1c
.RI "int \fBcc\fP"
.br
.ti -1c
.RI "uint32_t \fBcsrc\fP [15]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
