.TH "rtp_state" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtp_state
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBssrc\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "bool \fBinit\fP"
.br
.ti -1c
.RI "uint16_t \fBseq\fP"
.br
.ti -1c
.RI "uint16_t \fBodd_seq\fP"
.br
.ti -1c
.RI "bool \fBodd_seq_set\fP"
.br
.ti -1c
.RI "uint32_t \fBtimestamp\fP"
.br
.ti -1c
.RI "uint64_t \fBpackets\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes\fP"
.br
.ti -1c
.RI "uint64_t \fBdrops\fP"
.br
.ti -1c
.RI "uint64_t \fBdupes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
