.TH "sdr" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sdr
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBfrontend\fP * \fBfrontend\fP"
.br
.ti -1c
.RI "struct rtlsdr_dev * \fBdevice\fP"
.br
.ti -1c
.RI "int \fBdev\fP"
.br
.ti -1c
.RI "char \fBserial\fP [256]"
.br
.ti -1c
.RI "bool \fBbias\fP"
.br
.ti -1c
.RI "bool \fBagc\fP"
.br
.ti -1c
.RI "int \fBholdoff_counter\fP"
.br
.ti -1c
.RI "int \fBgain\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "pthread_t \fBread_thread\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
