.TH "sdrstate" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sdrstate
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBfrontend\fP * \fBfrontend\fP"
.br
.ti -1c
.RI "struct airspy_device * \fBdevice\fP"
.br
.ti -1c
.RI "uint32_t \fBsample_rates\fP [20]"
.br
.ti -1c
.RI "uint64_t \fBSN\fP"
.br
.ti -1c
.RI "bool \fBantenna_bias\fP"
.br
.ti -1c
.RI "double \fBconverter\fP"
.br
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "bool \fBsoftware_agc\fP"
.br
.ti -1c
.RI "bool \fBlinearity\fP"
.br
.ti -1c
.RI "int \fBgainstep\fP"
.br
.ti -1c
.RI "float \fBagc_energy\fP"
.br
.ti -1c
.RI "int \fBagc_samples\fP"
.br
.ti -1c
.RI "float \fBhigh_threshold\fP"
.br
.ti -1c
.RI "float \fBlow_threshold\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "pthread_t \fBcmd_thread\fP"
.br
.ti -1c
.RI "pthread_t \fBmonitor_thread\fP"
.br
.ti -1c
.RI "struct airspyhf_device * \fBdevice\fP"
.br
.ti -1c
.RI "void * \fBphd\fP"
.br
.ti -1c
.RI "int \fBnumber\fP"
.br
.ti -1c
.RI "complex float \fBDC\fP"
.br
.ti -1c
.RI "float \fBsinphi\fP"
.br
.ti -1c
.RI "float \fBimbalance\fP"
.br
.ti -1c
.RI "double \fBcalibration\fP"
.br
.ti -1c
.RI "uint8_t \fBbias_tee\fP"
.br
.ti -1c
.RI "bool \fBagc\fP"
.br
.ti -1c
.RI "PaStream * \fBPa_Stream\fP"
.br
.ti -1c
.RI "char \fBsdr_name\fP [50]"
.br
.ti -1c
.RI "int \fBoverrun\fP"
.br
.ti -1c
.RI "int \fBoverflows\fP"
.br
.ti -1c
.RI "pthread_t \fBproc_thread\fP"
.br
.ti -1c
.RI "struct libusb_device_handle * \fBdev_handle\fP"
.br
.ti -1c
.RI "uint64_t \fBserial\fP"
.br
.ti -1c
.RI "struct libusb_config_descriptor * \fBconfig\fP"
.br
.ti -1c
.RI "unsigned int \fBpktsize\fP"
.br
.ti -1c
.RI "unsigned int \fBtransfer_size\fP"
.br
.ti -1c
.RI "unsigned int \fBtransfer_index\fP"
.br
.ti -1c
.RI "struct libusb_transfer ** \fBtransfers\fP"
.br
.ti -1c
.RI "unsigned char ** \fBdatabuffers\fP"
.br
.ti -1c
.RI "long long \fBlast_callback_time\fP"
.br
.ti -1c
.RI "int \fBxfers_in_progress\fP"
.br
.ti -1c
.RI "unsigned int \fBqueuedepth\fP"
.br
.ti -1c
.RI "unsigned int \fBreqsize\fP"
.br
.ti -1c
.RI "unsigned long \fBsuccess_count\fP"
.br
.ti -1c
.RI "unsigned long \fBfailure_count\fP"
.br
.ti -1c
.RI "double \fBreference\fP"
.br
.ti -1c
.RI "bool \fBrandomizer\fP"
.br
.ti -1c
.RI "bool \fBdither\fP"
.br
.ti -1c
.RI "uint32_t \fBgpios\fP"
.br
.ti -1c
.RI "uint64_t \fBlast_sample_count\fP"
.br
.ti -1c
.RI "int64_t \fBlast_count_time\fP"
.br
.ti -1c
.RI "bool \fBmessage_posted\fP"
.br
.ti -1c
.RI "int \fBundersample\fP"
.br
.ti -1c
.RI "pthread_t \fBagc_thread\fP"
.br
.ti -1c
.RI "sdrplay_api_DeviceT \fBdevice\fP"
.br
.ti -1c
.RI "sdrplay_api_DeviceParamsT * \fBdevice_params\fP"
.br
.ti -1c
.RI "sdrplay_api_RxChannelParamsT * \fBrx_channel_params\fP"
.br
.ti -1c
.RI "enum sdrplay_status \fBdevice_status\fP"
.br
.ti -1c
.RI "uint64_t \fBevents\fP"
.br
.ti -1c
.RI "unsigned int \fBnext_sample_num\fP"
.br
.ti -1c
.RI "double \fBcarrier\fP"
.br
.ti -1c
.RI "float \fBamplitude\fP"
.br
.ti -1c
.RI "float \fBnoise\fP"
.br
.ti -1c
.RI "enum modulation \fBmodulation\fP"
.br
.ti -1c
.RI "char * \fBsource\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
