.TH "service_tab" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
service_tab
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBbuffer\fP"
.br
.ti -1c
.RI "char * \fBline_type\fP"
.br
.ti -1c
.RI "char * \fBinterface\fP"
.br
.ti -1c
.RI "char * \fBprotocol\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBtype\fP"
.br
.ti -1c
.RI "char * \fBdomain\fP"
.br
.ti -1c
.RI "char * \fBdns_name\fP"
.br
.ti -1c
.RI "char * \fBaddress\fP"
.br
.ti -1c
.RI "char * \fBport\fP"
.br
.ti -1c
.RI "char * \fBtxt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
