.TH "session::reseq" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
session::reseq
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBrtp_header\fP \fBrtp\fP"
.br
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "bool \fBinuse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
