.TH "userdata" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
userdata
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBservice_name\fP"
.br
.ti -1c
.RI "char * \fBservice_type\fP"
.br
.ti -1c
.RI "int \fBservice_port\fP"
.br
.ti -1c
.RI "char * \fBdns_name\fP"
.br
.ti -1c
.RI "char * \fBdescription\fP"
.br
.ti -1c
.RI "uint32_t \fBaddress\fP"
.br
.ti -1c
.RI "struct AvahiEntryGroup * \fBgroup\fP"
.br
.ti -1c
.RI "AvahiSimplePoll * \fBsimple_poll\fP"
.br
.ti -1c
.RI "pthread_t \fBavahi_thread\fP"
.br
.ti -1c
.RI "int \fBready\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBavahi_mutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBavahi_ready\fP"
.br
.ti -1c
.RI "int \fBservice_name_collision\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
