.TH "wav" 3 "KA9Q-Radio" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wav
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBChunkID\fP [4]"
.br
.ti -1c
.RI "int32_t \fBChunkSize\fP"
.br
.ti -1c
.RI "char \fBFormat\fP [4]"
.br
.ti -1c
.RI "char \fBSubchunk1ID\fP [4]"
.br
.ti -1c
.RI "int32_t \fBSubchunk1Size\fP"
.br
.ti -1c
.RI "int16_t \fBAudioFormat\fP"
.br
.ti -1c
.RI "int16_t \fBNumChannels\fP"
.br
.ti -1c
.RI "int32_t \fBSampleRate\fP"
.br
.ti -1c
.RI "int32_t \fBByteRate\fP"
.br
.ti -1c
.RI "int16_t \fBBlockAlign\fP"
.br
.ti -1c
.RI "int16_t \fBBitsPerSample\fP"
.br
.ti -1c
.RI "char \fBSubChunk2ID\fP [4]"
.br
.ti -1c
.RI "int32_t \fBSubchunk2Size\fP"
.br
.ti -1c
.RI "int16_t \fBExtensionChunkSize\fP"
.br
.ti -1c
.RI "int16_t \fBValidBitsPerSample\fP"
.br
.ti -1c
.RI "int32_t \fBChannelMask\fP"
.br
.ti -1c
.RI "char \fBSubformat\fP [16]"
.br
.ti -1c
.RI "char \fBFactID\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBFactSize\fP"
.br
.ti -1c
.RI "uint32_t \fBSamplesLength\fP"
.br
.ti -1c
.RI "char \fBAuxID\fP [4]"
.br
.ti -1c
.RI "int32_t \fBAuxSize\fP"
.br
.ti -1c
.RI "int16_t \fBStartYear\fP"
.br
.ti -1c
.RI "int16_t \fBStartMon\fP"
.br
.ti -1c
.RI "int16_t \fBStartDOW\fP"
.br
.ti -1c
.RI "int16_t \fBStartDay\fP"
.br
.ti -1c
.RI "int16_t \fBStartHour\fP"
.br
.ti -1c
.RI "int16_t \fBStartMinute\fP"
.br
.ti -1c
.RI "int16_t \fBStartSecond\fP"
.br
.ti -1c
.RI "int16_t \fBStartMillis\fP"
.br
.ti -1c
.RI "int16_t \fBStopYear\fP"
.br
.ti -1c
.RI "int16_t \fBStopMon\fP"
.br
.ti -1c
.RI "int16_t \fBStopDOW\fP"
.br
.ti -1c
.RI "int16_t \fBStopDay\fP"
.br
.ti -1c
.RI "int16_t \fBStopHour\fP"
.br
.ti -1c
.RI "int16_t \fBStopMinute\fP"
.br
.ti -1c
.RI "int16_t \fBStopSecond\fP"
.br
.ti -1c
.RI "int16_t \fBStopMillis\fP"
.br
.ti -1c
.RI "int32_t \fBCenterFrequency\fP"
.br
.ti -1c
.RI "char \fBAuxUknown\fP [128]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for KA9Q-Radio from the source code\&.
