[global]
hardware = airspy
status = 70cm.local
data = gen.local
encoding = opus
mode = pm
ttl = 1
verbose = 0
buffer = 3
fft-threads = 0
static = no
affinity = yes
fft-internal-threads = 0


description = "70cm discone @ KA9Q"
