[FMT]
# arrl freq measuring test
disable = yes
ttl = 0
data = fmt.local
samprate = 16k
encoding = s16be
mode = iq
hang-time = 0
recovery-rate = 60
low = -7k8
high = 7k8
freq = "2m5 5m0 10m0 15m0 20m0 25m0 3m33 7m85 14m67 7064k 7065k 3598k 3599k"


