[FREEDV]
data = freedv.local
samprate = 12k
encoding = s16be
mode = usb
freq = "14m236"
hang-time = 0
recovery-rate = 60

[FREEDV-L]
disable = yes
data = freedv.local
samprate = 12k
encoding = s16be
mode = lsb
freq = "7177k"
hang-time = 0
recovery-rate = 60
