#!/usr/bin/dh-exec
# debian/ka9q-radio.install
usr/bin/* usr/bin/ !usr/bin/control !usr/bin/monitor
usr/sbin/*
usr/share/ka9q-radio/*
usr/lib/ka9q-radio/sig_gen.so
etc/radio/*
etc/sysusers.d/*
etc/logrotate.d/*
etc/sysctl.d/*
etc/modprobe.d/*
usr/lib/hfdl/*
etc/cron.d/*
usr/lib/udev/rules.d/*
usr/lib/systemd/system/*
usr/share/man/man1/* !usr/share/man/man1/control.1 !usr/share/man/man1/monitor.1
usr/share/man/man8/*
