#!/bin/sh
set -e

case "$1" in
    configure)
	bin=$(command -v monitor 2>/dev/null || true)
	if [ -n "$bin" ]; then
	    setcap cap_net_admin+ep "$bin" || true
	fi
        ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if deb-systemd-helper debian-installed 'cwd.service'; then
		# The following line should be removed in trixie or trixie+1
		deb-systemd-helper unmask 'cwd.service' >/dev/null || true

		if deb-systemd-helper --quiet was-enabled 'cwd.service'; then
			# Create new symlinks, if any.
			deb-systemd-helper enable 'cwd.service' >/dev/null || true
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'cwd.service' >/dev/null || true
fi
# End automatically added section

