#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = upgrade ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'ft4-decode.service' 'ft4-record.service' 'ft8-decode.service' 'ft8-record.service' 'wspr-decoded.service' >/dev/null || true
fi
# End automatically added section
