[global]
hardware = airspy
status = 2m.local
data = gen.local
encoding = opus
mode = pm
ttl = 1
verbose = 0
buffer = 3
static = no
fft-threads = 1
fft-internal-threads = 0
affinity = yes


description = "2m discone @ KA9Q"
