[global]
hardware = airspyhf
status = airspyhf.local
data = airspy-data.local
mode = usb
fft-threads = 1 # more not needed at this low samprate
fft-internal-threads = 0
ttl=0
encoding = opus

[airspyhf]
device = "airspyhf"
description = "antenna @ yourcall"
hf-agc = yes
lib-dsp = yes # corrects frequency offset and I/Q imbalance in driver library?
samprate = 768k # driver defaults to the highest advertised, 912k, but seems to drop USB data
#samprate = 912k
