[global]
hardware = bladerf
status = bladerf.local
data = bladerf-data.local
encoding = opus
mode = pm
ttl = 0
verbose = 0
buffer = 3
static = no
fft-threads = 0
fft-internal-threads = 0
affinity = no

[bladerf]
device = bladerf
description = "your antenna @ call"
linearity = yes
#lna-agc = yes
#mixer-agc = yes

