[global]
hardware = fobos
status = fobos.local
data = fobos-data.local
encoding = opus
mode = pm
ttl = 0
verbose = 0
buffer = 3
fft-threads = 0
static = no
affinity = no
fft-internal-threads = 0

[fobos]
device = fobos
description = "antenna @ callsign"
#samprate = 25000000
#direct_sampling = n
#clk_source = 0 # 1 == external, 0 = internal?

