# basic config file for AMSAT UK funcube dongle
# very old and limited device, haven't used in a long time, untested
[global]
hardware = funcube
status = funcube.local
data = funcube-data.local
preset = am
ttl = 0

[rx888]
description = "funcube dongle"
device = funcube
number = 0

