[global]
hardware = hydrasdr
status = hydra.local
data = hydra-data.local
encoding = opus
mode = pm
ttl = 0
#verbose = 2
#buffer = 0
static = no
fft-threads = 1
affinity = no
fft-internal-threads = 0

[hydrasdr]
device = hydrasdr
description = "antenna @ yourcall"
linearity = no
#frequency = 148m6
#lna-agc = on
#mixer-agc = on
#agc-high-threshold = -20
#agc-low-threshold = -30
lna-agc = yes
mixer-agc = yes
